# Use Node.js image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker cache
COPY package.json package-lock.json ./

# Install dependencies and fix vulnerabilities
RUN npm install && \
    npm audit fix --force && \
    npm install @supabase/supabase-js

# Copy the rest of your application code
COPY . .



# Expose the port your app runs on
EXPOSE 3000

# Start the application in development mode
CMD ["npm", "run", "dev"]
